/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nim;

import java.awt.Graphics;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcus Stewart
 */
public class GUINIM extends javax.swing.JFrame {
    Player player1 = new Player("Player1");
    Player player2 =  new Player("Player2");
    
    int marblesTaken;
    Player cP;
    Graphics g;
    Random rand =  new Random();
    Pile pile = new Pile(14);
    

    /**
     * Creates new form GUINIM
     */
    public GUINIM() {
        initComponents();
        
        
        take1Button.setEnabled(false);
        take01Button.setEnabled(false);
        take02Button.setEnabled(false);
        take03Button.setEnabled(false);
        take2Button.setEnabled(false);
        take3Button.setEnabled(false);
    }
    
    
            @Override
    public void paint(Graphics g)
    { 
      super.paint(g);
      pile.drawPile(g, 100, 100);
    }
    
        public void adjustButtonState()
    {
        if(cP.equals(player1))
        {
                take01Button.setEnabled(false);
                take1Button.setEnabled(true);
                take02Button.setEnabled(false);
                take2Button.setEnabled(true);
                take03Button.setEnabled(false);
                take3Button.setEnabled(true);
        }
        else
        {
                take01Button.setEnabled(true);
                take1Button.setEnabled(false);
                take02Button.setEnabled(true);
                take2Button.setEnabled(false);
                take03Button.setEnabled(true);
                take3Button.setEnabled(false);
          
        }
        
        if(pile.getSize() == 2)
        {
            take03Button.setEnabled(false);
            take3Button.setEnabled(false);
        }
        
        if(pile.getSize() == 1)
        {
            take02Button.setEnabled(false);
            take2Button.setEnabled(false);
            take03Button.setEnabled(false);
            take3Button.setEnabled(false);
        }
        
        cLabel.setText("" + pile.getSize() + "");
        
        if(pile.getSize() == 0)
        {
            take01Button.setEnabled(false);
            take1Button.setEnabled(false);
            take02Button.setEnabled(false);
            take2Button.setEnabled(false);
            take03Button.setEnabled(false);
            take3Button.setEnabled(false);
           //nextPlayer();
           dTextArea.append("Congrats " + cP.getName() + " won the game!");

        }
    }
    
    public void takeTurn(int marbles)
    {
        pile.remove(marbles);
        repaint();
        
//        if(pile.getSize() == 0)
//        {
//            System.out.println("The winner is " + cP + "!");
//        }
       
    }
    
    
    
    public void nextPlayer()
    {
        if(cP.equals(player1))
        {
            cP = player2;
        }
        else{
            cP = player1;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        take1Button = new javax.swing.JButton();
        take2Button = new javax.swing.JButton();
        take3Button = new javax.swing.JButton();
        take01Button = new javax.swing.JButton();
        take02Button = new javax.swing.JButton();
        take03Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dTextArea = new javax.swing.JTextArea();
        newGameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        player1JLabel = new javax.swing.JLabel();
        player2JLabel = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        take1Button.setText("Take 1");
        take1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take1ButtonActionPerformed(evt);
            }
        });

        take2Button.setText("Take 2");
        take2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take2ButtonActionPerformed(evt);
            }
        });

        take3Button.setText("Take 3");
        take3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take3ButtonActionPerformed(evt);
            }
        });

        take01Button.setText("Take 1");
        take01Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take01ButtonActionPerformed(evt);
            }
        });

        take02Button.setText("Take 2");
        take02Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take02ButtonActionPerformed(evt);
            }
        });

        take03Button.setText("Take 3");
        take03Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                take03ButtonActionPerformed(evt);
            }
        });

        dTextArea.setColumns(20);
        dTextArea.setRows(5);
        jScrollPane1.setViewportView(dTextArea);

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        cLabel.setText("Count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(take2Button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(take1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player1JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(take3Button))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(cLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(player2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(take02Button, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(take03Button, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(take01Button)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newGameButton)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(player2JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(player1JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(take01Button)
                            .addComponent(take1Button)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(take2Button)
                    .addComponent(take02Button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(take3Button)
                    .addComponent(take03Button))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newGameButton)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>                        

    private void take01ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
       //pile.remove(1);
       takeTurn(1);
       nextPlayer();
       
       dTextArea.append(player2.getName() + " took one marble from the pile. \n There are " + pile.getSize() + " marbles left in the pile.");
       
       dTextArea.append(" \n \n " + "It's " + player1.getName() + "'s turn. \n");
        
       adjustButtonState();
    }                                            

    private void take02ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
       //pile.remove(2);
       takeTurn(2);
       nextPlayer();
        
       dTextArea.append(player2.getName() + " took two marbles from the pile. \n There are " + pile.getSize() + " marbles left in the pile.");
       
       dTextArea.append(" \n \n " + "It's " + player1.getName() + "'s turn. \n");
       
       adjustButtonState();
    }                                            

    private void take03ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
      //pile.remove(3);
       takeTurn(3);
       nextPlayer();
        
       dTextArea.append(player2.getName() + " took three marbles from the pile. \n There are " + pile.getSize() + " marbles left in the pile.");
       
       dTextArea.append(" \n \n " + "It's " + player1.getName() + "'s turn. \n");
       
       adjustButtonState();
    }                                            

    private void take1ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        takeTurn(1);
        //pile.remove(1);
        
        
       dTextArea.append(player1.getName() + " took one marble from the pile. \n There are " + pile.getSize() + " marbles left in the pile.");
       nextPlayer();
       dTextArea.append(" \n \n " + "It's " + player2.getName() + "'s turn. \n");
        
       adjustButtonState();
    }                                           

    private void take2ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        takeTurn(2);
        //pile.remove(2);
       
        
       dTextArea.append(player1.getName() + " took two marbles from the pile. \n There are " + pile.getSize() + " marbles left in the pile.");
       nextPlayer();
       dTextArea.append(" \n \n " + "It's " + player2.getName() + "'s turn. \n");
       
       adjustButtonState();
    }                                           

    private void take3ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        takeTurn(3);
        //pile.remove(3);
        
        
       dTextArea.append(player1.getName() + " took three marbles from the pile. \n There are " + pile.getSize() + " marbles left in the pile.");
       nextPlayer();
       dTextArea.append(" \n \n " + "It's " + player2.getName() + "'s turn. \n");
        
       adjustButtonState();
    }                                           

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        pile.setPileSize(14);
        int sP = rand.nextInt(2) +1;
        if(sP == 1)
        {
            cP = player1;
        }
        else
        {
            cP = player2;
        }
       // cP = player1;
        String p1Name = JOptionPane.showInputDialog(null, "Please enter the player1 name.");
        String p2Name = JOptionPane.showInputDialog(null, "Please enter the player2 name.");
        player1.setName(p1Name);
        player2.setName(p2Name);
        player1JLabel.setText(p1Name);
        player2JLabel.setText(p2Name);
        
        adjustButtonState();
        

  
        //dTextArea.append("");
        //dTextArea.append("It is " + cP.getName() + " turn \nThere are 17 marbles in the pile. \n \n ");
        dTextArea.setText(cP.getName() + " has been selected to go first");
        //cLabel.setText("" + pile.getSize() + "");
        //pile.setPileSize(17);
        //paint(g);
        
        repaint();
        
    }                                             


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINIM().setVisible(true);
            }
        });
    }
    

    


    // Variables declaration - do not modify                     
    private javax.swing.JLabel cLabel;
    private javax.swing.JTextArea dTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel player1JLabel;
    private javax.swing.JLabel player2JLabel;
    private javax.swing.JButton take01Button;
    private javax.swing.JButton take02Button;
    private javax.swing.JButton take03Button;
    private javax.swing.JButton take1Button;
    private javax.swing.JButton take2Button;
    private javax.swing.JButton take3Button;
    // End of variables declaration                   
}